# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 06:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import threedbang.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StlFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='요청사항을 기재해주세요', max_length=255)),
                ('file', models.FileField(upload_to=threedbang.models.user_path)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('volume', models.IntegerField(default=0)),
                ('price', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('thumnail_image', models.ImageField(blank=True, upload_to='')),
                ('filenamemake', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
