# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threedbang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stlfile',
            name='thumnail_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
