# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threedbang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stlfile',
            name='price',
            field=models.CharField(default='검토중', max_length=255),
        ),
        migrations.AlterField(
            model_name='stlfile',
            name='time',
            field=models.CharField(default='30분만 기다려주세요!', max_length=255),
        ),
    ]
