# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threedbang', '0002_auto_20171203_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stlfile',
            name='time',
            field=models.CharField(default='검토중', max_length=255),
        ),
    ]
