# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threedbang', '0002_stlfile_thumnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stlfile',
            name='comment',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
