# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threedbang', '0004_auto_20171123_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stlfile',
            name='comment',
            field=models.CharField(default='요청사항을 기재해주세요', max_length=255),
        ),
    ]
